## alt kume uzerinde islem yapmak

In [1]:
import numpy as np
a = np.random.randint(10, size=(5, 5))
a

array([[8, 6, 4, 8, 7],
       [6, 9, 1, 8, 0],
       [8, 4, 1, 3, 9],
       [2, 1, 5, 7, 1],
       [0, 4, 6, 9, 0]])

In [2]:
altA = a[0:3, 0:2]
altA

array([[8, 6],
       [6, 9],
       [8, 4]])

In [3]:
altA[0, 0] = 99999
altA[1, 1] = 888
altA

array([[99999,     6],
       [    6,   888],
       [    8,     4]])

In [4]:
a

# a'nın alt kümesi olan altA'da değişiklik yaptığımızda ana küme olan a'da da değişiklik oldu.

array([[99999,     6,     4,     8,     7],
       [    6,   888,     1,     8,     0],
       [    8,     4,     1,     3,     9],
       [    2,     1,     5,     7,     1],
       [    0,     4,     6,     9,     0]])

In [5]:
x = np.random.randint(10, size=(5, 5))
x

array([[2, 9, 7, 4, 9],
       [3, 6, 1, 2, 3],
       [7, 0, 0, 8, 9],
       [4, 7, 2, 1, 7],
       [9, 1, 7, 9, 0]])

In [6]:
altB = x[0:3, 0:2].copy()
altB

# copy() eklediğimizde, alt kümeyi ana kümeden bağımsızlaştırmış oluyor.

array([[2, 9],
       [3, 6],
       [7, 0]])

In [7]:
altB[0, 0] = 999
altB

array([[999,   9],
       [  3,   6],
       [  7,   0]])

In [8]:
a

array([[99999,     6,     4,     8,     7],
       [    6,   888,     1,     8,     0],
       [    8,     4,     1,     3,     9],
       [    2,     1,     5,     7,     1],
       [    0,     4,     6,     9,     0]])