## matematiksel islemler


In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [2]:
x - 1

array([0, 1, 2, 3, 4])

In [3]:
x * 5

array([ 5, 10, 15, 20, 25])

In [4]:
x / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [5]:
x * 5 / 10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

========================================================


#### ufunc


In [6]:
np.add(x, 3)

array([4, 5, 6, 7, 8])

In [7]:
np.subtract(x, 3)

array([-2, -1,  0,  1,  2])

In [8]:
np.multiply(x, 3)

array([ 3,  6,  9, 12, 15])

In [9]:
np.divide(x, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [10]:
x**2

array([ 1,  4,  9, 16, 25])

In [11]:
x**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [12]:
np.power(x, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [13]:
x % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [14]:
np.mod(x, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [15]:
np.absolute([np.array([-3])])

# mutlak değer

array([[3]])

In [16]:
np.sin(360)

0.9589157234143065

In [17]:
np.cos(180)

-0.5984600690578581

In [18]:
x = np.array([1, 2, 3])
np.log(x)

# logaritma işlemi

array([0.        , 0.69314718, 1.09861229])

In [19]:
np.log2(x)

array([0.       , 1.       , 1.5849625])