## index ile elemanlara erismek

In [1]:
import numpy as np
a = np.random.randint(10, size=10)
a

array([3, 8, 7, 0, 2, 8, 6, 9, 4, 8])

In [2]:
a[0]

3

In [3]:
a[-1]

8

In [4]:
a[0] = 100
a

# array'deki elemanı değiştirme

array([100,   8,   7,   0,   2,   8,   6,   9,   4,   8])

In [5]:
x = np.random.randint(10, size=(3, 5))
x

array([[2, 3, 3, 9, 0],
       [9, 9, 8, 1, 9],
       [6, 8, 7, 2, 6]])

In [6]:
x[0, 0]

2

In [7]:
x[1, 1] = 999
x

array([[  2,   3,   3,   9,   0],
       [  9, 999,   8,   1,   9],
       [  6,   8,   7,   2,   6]])

In [8]:
x[1, 4] = 2.2
x

# sadece 2 değerini ekler. virgülden sonrasını eklemez. int array olduğu için

array([[  2,   3,   3,   9,   0],
       [  9, 999,   8,   1,   2],
       [  6,   8,   7,   2,   6]])