## array alt kume islemleri


In [1]:
import numpy as np

In [2]:
x = np.arange(20, 30)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
x[0:3]

array([20, 21, 22])

In [4]:
x[::3]

array([20, 23, 26, 29])

In [5]:
x[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
x[1::2]
# 1. indexten 2'şer 2'şer atlayarak devam eder

array([21, 23, 25, 27, 29])

In [7]:
x[0::2]

array([20, 22, 24, 26, 28])

#### ========================================================

#### 2 boyutlu slice islemleri


In [8]:
z = np.random.randint(10, size=(5, 5))
z

array([[9, 4, 5, 2, 7],
       [7, 1, 0, 2, 8],
       [9, 8, 0, 1, 8],
       [2, 0, 5, 4, 4],
       [3, 1, 2, 4, 3]])

In [9]:
z[:,0]

# bütün satırları seç, sadece 0. indexteki sütunu seç

array([9, 7, 9, 2, 3])

In [10]:
z[3,:]

array([2, 0, 5, 4, 4])

In [11]:
z[0,:]

array([9, 4, 5, 2, 7])

In [12]:
z[0:2, 0:3]

# 0'dan 2'ye kadar satırları al, 0'dan 3'e kadar sütunları al

array([[9, 4, 5],
       [7, 1, 0]])

In [13]:
z[:, 0:2]

# tüm satırları, 0. ve 1. sütunları al

array([[9, 4],
       [7, 1],
       [9, 8],
       [2, 0],
       [3, 1]])

In [14]:
z[1:3, 0:2]

array([[7, 1],
       [9, 8]])