## kosullu eleman islemleri


In [1]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [2]:
x > 5

array([False, False, False, False, False])

In [3]:
x < 3

array([ True,  True, False, False, False])

In [4]:
x[x < 3]

# x arrayi içinde fancy index kullanarak istediğimiz şartı sağlayan elemanların indexlerini yakalayabiliriz

array([1, 2])

In [5]:
x[x >= 3]

array([3, 4, 5])

In [6]:
x[x == 3]

array([3])

In [7]:
x[x != 3]

array([1, 2, 4, 5])

In [8]:
x

array([1, 2, 3, 4, 5])

In [9]:
x * 2

# bütün x elemanlarını 2 ile çarpar

array([ 2,  4,  6,  8, 10])

In [10]:
x / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [11]:
x * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [12]:
x ** 2

# karesini alır

array([ 1,  4,  9, 16, 25])