In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([3.14, 4, 2, 13], dtype="float32")
# değerleri float32 olarak kabul eder ve o şekilde liste oluşturur

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [6]:
np.array([3.14, 4, 2, 13], dtype="int")
# değerleri int olarak kabul edip o şekilde liste oluşturur

array([ 3,  4,  2, 13])

##### ========================================================

## sifirdan array olusturma

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.full((3, 5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [10]:
np.arange(2, 30, 3)
# 2'den 30'a kadar +3 fark ile dizi oluşturdu - doğrusal dizi

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [11]:
np.linspace(0, 1, 10)
# 0 ile 1 arasında 10 tane değer oluşturur

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
np.random.normal(10, 4, (3, 4))
# bu örnekte parantez içindeki 10 = ortalama, 4 = standart sapmayı temsil eder

array([[10.07181851, 11.98419212, 16.96476203,  6.10402709],
       [ 6.24505991, 12.99875053,  3.65157897, 10.24965429],
       [13.0878873 ,  6.66271048, 18.04315253,  7.02384989]])

In [13]:
np.random.randint(0, 10, (3, 3))
# integer değerlerden rastgele oluşturulmuş veri

array([[0, 0, 8],
       [3, 7, 9],
       [4, 2, 7]])

eğer bunları kullanmak istersek kaydetmemiz gerekir.

a = .... gibi