### numpy array özellikleri


- **ndim**: boyut sayısı
- **shape**: _boyut bilgisi_
- **size**: toplam eleman sayısı
- **dtype**: array veri tipi


In [1]:
import numpy as np

In [2]:
np.random.randint(10, size=10)

array([8, 1, 7, 4, 5, 2, 0, 6, 9, 5])

In [14]:
a = np.random.randint(10, size=10)
a

array([8, 3, 6, 3, 6, 8, 6, 0, 6, 5])

In [4]:
a.ndim

1

In [5]:
a.shape
# tek boyutlu array olduğu için sadece virgülden öncesinde bilgi var. array eleman sayısı 10.

(10,)

In [6]:
a.size

10

In [7]:
a.dtype

dtype('int32')

In [8]:
b = np.random.randint(10, size=(3, 5))
b

array([[5, 4, 7, 2, 1],
       [9, 3, 5, 2, 9],
       [2, 7, 4, 2, 4]])

In [9]:
b.ndim

2

In [10]:
b.shape

(3, 5)

In [11]:
b.size

15

In [12]:
b.dtype

dtype('int32')