## fancy index ile elemanlara erismek

In [1]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [2]:
v[1]

3

In [3]:
v[3]

9

In [4]:
v[5]

15

In [5]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [6]:
alGetir = [1, 3, 5]
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
v[alGetir]

array([ 3,  9, 15])

#### ========================================================
#### 2 boyutta fancy index

In [8]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
satir = np.array([0, 1])
sutun = np.array([1, 2])
x[satir, sutun]

array([1, 5])

#### ========================================================

#### basit index ile fancy index

In [10]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
x[0, [1, 2]]

# 0. satırdaki 1. ve 2. sütunları alır.

array([1, 2])

In [12]:
satir = np.array([0, 1, 2])
sutun = np.array([2, 1, 2])

# 0. satırdaki 2. sütun, 1. satırdaki 1. sütun, 2. satırdaki 2. sütunu alır

x[satir, sutun]

array([2, 4, 8])

#### ========================================================
#### slice ile fancy

In [13]:
x[0:, [1, 2]]

# 0: = 0. satırdan son satıra kadar git anlamında.

array([[1, 2],
       [4, 5],
       [7, 8]])