## siralama - sorting


In [1]:
import numpy as np

In [2]:
x = np.array([2, 1, 4, 3, 5])
x

array([2, 1, 4, 3, 5])

In [3]:
np.sort(x)

# bu şekilde kullandığımızda elimizdeki verinin orijinal halini bozmadan işlem yapılır

array([1, 2, 3, 4, 5])

In [4]:
x.sort()

# böyle kullandığımızda ise elimizde bulunan x array'inin orijinal düzeni bozulmuş olur

#### ========================================================

#### 2 boyutlu array sıralama


In [5]:
z = np.random.normal(20, 5, (3, 3))
z

# ortalaması 20, standart sapması 5 olan array oluşturur

array([[17.17808318, 22.72963684, 13.40826109],
       [15.76622319, 17.82207148, 16.24074173],
       [30.35051845, 20.65556829, 18.8518658 ]])

In [6]:
np.sort(z, axis=1)

# her satırı kendi içinde küçükten büyüğe olacak şekilde sıralar

array([[13.40826109, 17.17808318, 22.72963684],
       [15.76622319, 16.24074173, 17.82207148],
       [18.8518658 , 20.65556829, 30.35051845]])

In [7]:
np.sort(z, axis=0)

# her sütunu kendi arasında küçükten büyüğe sıralar

array([[15.76622319, 17.82207148, 13.40826109],
       [17.17808318, 20.65556829, 16.24074173],
       [30.35051845, 22.72963684, 18.8518658 ]])