In [34]:
import numpy as np

In [35]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [36]:
a = np.array([1,2,3,4,5])

In [37]:
type(a)

numpy.ndarray

In [38]:
np.array([3.14, 4, 2, 13], dtype="float32")
# değerleri float32 olarak kabul eder ve o şekilde liste oluşturur

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [39]:
np.array([3.14, 4, 2, 13], dtype="int")
# değerleri int olarak kabul edip o şekilde liste oluşturur

array([ 3,  4,  2, 13])

##### ========================================================

## sifirdan array olusturma

In [40]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
np.full((3, 5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [43]:
np.arange(2, 30, 3)
# 2'den 30'a kadar +3 fark ile dizi oluşturdu - doğrusal dizi

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [44]:
np.linspace(0, 1, 10)
# 0 ile 1 arasında 10 tane değer oluşturur

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [45]:
np.random.normal(10, 4, (3, 4))
# bu örnekte parantez içindeki 10 = ortalama, 4 = standart sapmayı temsil eder

array([[11.28215338,  8.91648564, -1.51065881, 12.77530082],
       [11.02415198, 14.85129173, 13.69605664, 13.36835371],
       [ 8.36423202,  6.29570386,  9.80370516, 10.02989815]])

In [46]:
np.random.randint(0, 10, (3, 3))
# integer değerlerden rastgele oluşturulmuş veri

array([[9, 1, 8],
       [2, 2, 5],
       [6, 8, 8]])

eğer bunları kullanmak istersek kaydetmemiz gerekir.

a = .... gibi