## yeniden şekillendirme - reshaping


In [1]:
import numpy as np

In [2]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- belirli bir array'i, verilen boyutlarda yeni bir array oluşturmada kullanılır.


In [3]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a = np.arange(1, 10)

In [5]:
a.ndim
# tek boyutlu array = vektör

1

In [6]:
b = a.reshape(1, 9)
b
# 2 tane köşeli parantez olduğundan 2 boyutlu bir array haline geldi. ama 1 boyutta olan verileri korudu.

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [7]:
b.ndim

2