## array birlestirme - concatenation


In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [3]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [4]:
z = np.array([7, 8, 9])

In [6]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [8]:
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
np.concatenate([a, a], axis=1)
# axis = 0 satırları, 1 sütunları ifade eder.
# axis default = 0, yani satır satır birleştirdi.
# axis = 1 olduğu zaman sütun sütun birleştirir.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])