## kismi en kucuk kareler regresonu - pls - tahmin


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import warnings

warnings.simplefilter(action="ignore", category=FutureWarning)

hit = pd.read_csv('Hitters.csv')
df = hit.copy()
df = df.dropna()
dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])
y = df['Salary']
x_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'],
             axis=1).astype('float64')
x = pd.concat([x_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.25, random_state=42)

In [2]:
from sklearn.cross_decomposition import PLSRegression, PLSSVD

In [3]:
pls_model = PLSRegression(n_components=2).fit(x_train, y_train)

In [4]:
pls_model.coef_

array([[ 35.32916493,  48.83425857,  18.50240933,  39.28117603,
         30.59952998,  40.03398345,  16.85990516,  28.22289896,
         32.73784993,  22.00875744,  33.60903032,  30.39402522,
         25.73279799,  54.98835148,   6.56590871,  -0.90894359,
         17.60903423, -37.24246339,  14.69680385]])

#### **Tahmin**

In [5]:
x_train.head()

AtBat   Hits  HmRun  Runs   RBI  Walks  Years  CAtBat   CHits  CHmRun  \
183  328.0   91.0   12.0  51.0  43.0   33.0    2.0   342.0    94.0    12.0   
229  514.0  144.0    0.0  67.0  54.0   79.0    9.0  4739.0  1169.0    13.0   
286  593.0  152.0   23.0  69.0  75.0   53.0    6.0  2765.0   686.0   133.0   
102  233.0   49.0    2.0  41.0  23.0   18.0    8.0  1350.0   336.0     7.0   
153  341.0   95.0    6.0  48.0  42.0   20.0   10.0  2964.0   808.0    81.0   

     CRuns   CRBI  CWalks  PutOuts  Assists  Errors  League_N  Division_W  \
183   51.0   44.0    33.0    145.0     59.0     8.0      True       False   
229  583.0  374.0   528.0    229.0    453.0    15.0      True       False   
286  369.0  384.0   321.0    315.0     10.0     6.0     False        True   
102  166.0  122.0   106.0    102.0    132.0    10.0     False       False   
153  379.0  428.0   221.0    158.0      4.0     5.0      True        True   

     NewLeague_N  
183         True  
229         True  
286        False  
102        False  
153         True

In [6]:
pls_model.predict(x_train)

array([ 344.91941493,  848.87070769,  692.93622642,  185.56577984,
        435.49196077,  987.49530026,  120.63097106,  289.9263406 ,
        663.41886918,  817.90486641, 1400.82155793,  889.55177741,
        966.02942625,  761.83859363,  817.87219643,  778.83233464,
        947.29337036,    2.76773968,  -72.48003564,  382.99117487,
        596.85479706,  977.61608943,  415.33783869,  464.78071379,
        -26.62516231,  722.22493096,  494.5057314 ,  242.23751188,
        206.9261497 ,  232.56490602,   64.4824203 ,  542.14513157,
        947.14732555,  194.89583773,  362.6202354 ,  295.26950277,
        439.33442044,  776.65786654,  317.39738256,  137.13823539,
        103.25963596,  206.20369642,  139.57105168,  120.59249853,
        230.30589651, 1104.22505297,  640.35250992,  482.26330677,
        338.69287437,  275.48478485,  443.09856705,  576.77544271,
        530.92923226,  537.95696355,  827.0093267 ,  504.93654004,
        363.82023709,  876.99960817,  356.80129675, 1190.55931

In [7]:
pls_model. predict (x_train) [0 : 10]

array([344.91941493, 848.87070769, 692.93622642, 185.56577984,
       435.49196077, 987.49530026, 120.63097106, 289.9263406 ,
       663.41886918, 817.90486641])

In [8]:
y_pred = pls_model.predict(x_train)

In [9]:
from sklearn.metrics import mean_squared_error

np.sqrt(mean_squared_error(y_train, y_pred))

310.1167593109696

In [10]:
from sklearn.metrics import r2_score

r2_score(y_train, y_pred)

0.5140424486535481

In [11]:
y_pred = pls_model.predict(x_test)

In [12]:
np.sqrt(mean_squared_error(y_test, y_pred))

398.09956327448526