## coklu dogrusal regresyon - model tuning - model dogrulama


In [1]:
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
from sklearn.linear_model import LinearRegression
import statsmodels.formula.api as smf
import statsmodels.api as sm
import numpy as np
import pandas as pd

ad = pd.read_csv('Advertising.csv')
df = ad.copy()
df.head()

x = df[['TV']]
y = df['sales']
x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size=0.20,
                                                    random_state=144)

lm = LinearRegression()
model = lm.fit(x_train, y_train)

# random_state degerini degistirdigimizde np.sqrt ve model.score degerleri de degisir
# burada onemli olan soru sudur: biz veri setinin bir kismini sececegiz fakat hangi kismini sececegiz?

# bu problemi giderebilmek icin cross validation yontemi kullanilir

In [2]:
np.sqrt(mean_squared_error(y_train, model.predict(x_train)))

3.107647496632468

In [3]:
model.score(x_train, y_train)

0.6459499057909992

In [4]:
cross_val_score(model, x, y, cv=10, scoring="r2")

# 10 katli cross validation

array([0.70015158, 0.43449405, 0.58322591, 0.78975123, 0.47952235,
       0.62298657, 0.66525353, 0.60389703, 0.16530872, 0.64237498])

In [5]:
cross_val_score(model, x, y, cv=10, scoring="r2").mean()

# modelimizin daha guvenilir, valide edilmis, dogrulanmis r^2 degeri budur
# ancak biz bu islemi butun veri seti icin yaptik

0.5686965937483904

In [6]:
model.score(x_train, y_train)

# az once elde ettigimiz skor. asagidaki valide edilmis skordan farkli

0.6459499057909992

In [7]:
cross_val_score(model, x_train, y_train, cv=10, scoring="r2").mean()

0.5596563213243794

In [8]:
-cross_val_score(model, x_train, y_train, cv=10, scoring="neg_mean_squared_error")

# en basa - koymamizin sebebi, sonucun -'li olarak geliyor olmasi

array([13.92062056,  9.29383535,  6.32443072,  8.50622704,  9.41266889,
       11.33575591,  9.26203478,  9.77714338,  9.90424031, 10.79827468])

In [9]:
rmse = np.sqrt(
    -cross_val_score(model, x_train, y_train, cv=10, scoring="neg_mean_squared_error")
)
rmse

# egitim setimiz icin 10 adet egitim hatasi olusturuldu

# 3. hucredeki np.sqrt(mean_squared_error(y_train, model.predict(x_train))) ciktisindan daha farkli sonuclar cikiyor
# veri setindeki sectigimiz parcalara gore farklı farklı egitim hatalari olusuyor

array([3.73103478, 3.04857924, 2.51484209, 2.91654368, 3.06800732,
       3.36686143, 3.04335913, 3.1268424 , 3.1471003 , 3.28607283])

In [10]:
rmse = np.sqrt(
    -cross_val_score(model, x_train, y_train, cv=10, scoring="neg_mean_squared_error")
).mean()
rmse

# yukarıdaki degerlerin ortalamasi alindiginda bu degerleri valide etmis oluyoruz ve gercek egitim hatasini buluyoruz.

3.1249243196480836

### ========================================================


In [11]:
np.sqrt(mean_squared_error(y_test, model.predict(x_test)))

3.74366601636939

In [12]:
rmse = np.sqrt(
    -cross_val_score(model, x_test, y_test, cv=10, scoring="neg_mean_squared_error")
).mean()
rmse

3.8494070328044403